spring.application.name=spring_thymeleaf

#zentrale Konfiguration für springboot application
#server.port=8080
#spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.suffix=.html
#spring.thymeleaf.mode=HTML
#spring.thymeleaf.encoding=UTF-8
#spring.thymeleaf.cache=false